clusters:
- name: Dev
  datacentre: Local
  nodes:
  - dev1.company.com
  - dev2.company.com
- name: Prod
  datacentre: Amazon
  nodes:
  - prd1.company.com
  - prd2.company.com
  - prd3.company.com
min_replicas: 1
max_replicas: 5
debug: true
database: application_test
api_path: /application-api
identifier: Application 1
mgo_dial: localhost
addr: :8088
base_url: /api/
